import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'msedge', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1100, height: 780 } })
await page.goto('http://localhost:4173/app', { waitUntil: 'networkidle' })
await page.waitForTimeout(1500)
await page.getByText('2020 frame cube').click()
await page.waitForTimeout(2500)
const b = await page.locator('canvas').first().boundingBox()
for (let i = 0; i < 7; i++) { await page.mouse.move(b.x + b.width/2, b.y + b.height/2); await page.mouse.wheel(0, -200); await page.waitForTimeout(70) }
await page.waitForTimeout(2000)
await page.screenshot({ path: 'shots/ab-zoom-postfx.png', clip: { x: b.x, y: b.y, width: b.width, height: b.height } })
await page.evaluate(() => window.twinbench.doc.getState().setView({ quality: 'off' }))
await page.waitForTimeout(2000)
await page.screenshot({ path: 'shots/ab-zoom-nopostfx.png', clip: { x: b.x, y: b.y, width: b.width, height: b.height } })
await page.evaluate(() => window.twinbench.doc.getState().setView({ quality: 'high', grid: false }))
await page.waitForTimeout(2000)
await page.screenshot({ path: 'shots/ab-zoom-nogrid.png', clip: { x: b.x, y: b.y, width: b.width, height: b.height } })
console.log('done')
await browser.close()
