import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'msedge', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } })
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(1000)
await page.evaluate(() => document.querySelector('#check')?.scrollIntoView({ block: 'center' }))
await page.waitForTimeout(900)
await page.locator('.demo').screenshot({ path: 'shots/demo-good.png' })
await page.getByRole('tab', { name: /Straight to 5/ }).click()
await page.waitForTimeout(600)
await page.locator('.demo').screenshot({ path: 'shots/demo-bad.png' })
await page.evaluate(() => document.querySelector('#parts')?.scrollIntoView({ block: 'center' }))
await page.waitForTimeout(1200)
await page.locator('.searchdemo').screenshot({ path: 'shots/demo-search.png' })
console.log('done')
await browser.close()
